all:
	python code/moteur.py
	cat automate.log
test:
	python code/test.py
help:
	@echo "'graph' - génére un fichier png à partir de graph.dot"

graph:
	dot -Tpng dotImage/graph.dot > dotImage/graph.png

	

